name: Snyk GitHub Actions example

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    name: Test and build
    environment: snyk-npm
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    
    - name: Snyk
      # You may pin to the exact commit or the version.
      # uses: snyk/actions@7fad562681122205233d1242c3bb39598c5393da
      uses: snyk/actions@0.3.0
      env:
          SNYK_TOKEN: ${{secrets.SNYK_AUTH}}
      with:
        command: test
        args: --severity-threshold=critical
